apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-1
  labels:
    app: load-test-1
spec:
  replicas: {{ .Values.backend1.replicas }}
  selector:
    matchLabels:
      app: load-test-1
  template:
    metadata:
      labels:
        app: load-test-1
    spec:
      containers:
      - name: load-test
        image: load-test
        args:
        - attack
        - -targets
        - /etc/vegeta/targets
        - -rate={{ .Values.backend1.rate }}
        - -keepalive=false
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config
          mountPath: /etc/vegeta
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: load-test-1
