{{ if .Values.hpa.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: backend-2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-2
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: hubble_http_response_rate
      targetAverageValue: {{ .Values.backend2.qpsTarget | quote }}
{{ end }}
